package perry

/**
 * Created with IntelliJ IDEA.
 * User: MarkPerry
 * Date: 25/10/12
 * Time: 2:11 PM
 * To change this template use File | Settings | File Templates.
 */

/**
 * Consider all integer combinations of ab for 2 a 5 and 2 b 5:
 *
 * 22=4, 23=8, 24=16, 25=32
 * 32=9, 33=27, 34=81, 35=243
 * 42=16, 43=64, 44=256, 45=1024
 * 52=25, 53=125, 54=625, 55=3125
 *
 * If they are then placed in numerical order, with any repeats removed, we get the
 * following sequence of 15 distinct terms:
 *
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 *
 * How many distinct terms are in the sequence generated by ab for 2 a 100 and 2 b 100?
 *
 */
class P029 {


	def p() {

		def a = combos(5)
		def b = combos(100)
		println a
		println "size: ${a.size()}, list: ${a}"
		println "size: ${b.size()}, list: ${b}"
		// assert(b.size() == 9183)
	}

	def combos(Integer max) {

		def a = (2..max).collect{a -> (2..max).collect{a ** it}}.flatten()
		def b = a.sort().unique()
		b

	}

}
